Update xg-040g-调试.yml

diff --git a/.github/workflows/xg-040g-调试.yml b/.github/workflows/xg-040g-调试.yml
--- a/.github/workflows/xg-040g-调试.yml
+++ b/.github/workflows/xg-040g-调试.yml
@@ -47,7 +47,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v6
 
-            - name: Set dynamic branch and config
+      - name: Set dynamic branch and config
         id: dynamic_config
         run: |
           if [[ "${{ inputs.patch_type }}" == "patch-master" ]]; then
@@ -75,28 +75,28 @@ jobs:
       - name: Initialization environment
         id: init
         env:
-        DEBIAN_FRONTEND: noninteractive
+          DEBIAN_FRONTEND: noninteractive
         run: |
-        sudo -E apt-get -y update
-        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
+          sudo -E apt-get -y update
+          sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
 
       - name: mkbootimg build
         run: |
-        wget https://github.com/xuxin1955/depend_ubuntu2204_openwrt/releases/download/ubuntu_26.04_LTS_mkbootimg/mkbootimg_34.0.5-12build1_all.deb
-        sudo dpkg -i mkbootimg_34.0.5-12build1_all.deb
-        sudo apt-get install -f -y
-        # 验证安装
-        mkbootimg --help || true
-        MKBOOTIMG_PATH=$(which mkbootimg)
-        if [ -n "$MKBOOTIMG_PATH" ]; then
-        echo "mkbootimg found at: $MKBOOTIMG_PATH"
-        file "$MKBOOTIMG_PATH"
-        else
-        echo "❌ mkbootimg not found in PATH!"
-        fi
+          wget https://github.com/xuxin1955/depend_ubuntu2204_openwrt/releases/download/ubuntu_26.04_LTS_mkbootimg/mkbootimg_34.0.5-12build1_all.deb
+          sudo dpkg -i mkbootimg_34.0.5-12build1_all.deb
+          sudo apt-get install -f -y
+          # 验证安装
+          mkbootimg --help || true
+          MKBOOTIMG_PATH=$(which mkbootimg)
+          if [ -n "$MKBOOTIMG_PATH" ]; then
+          echo "mkbootimg found at: $MKBOOTIMG_PATH"
+          file "$MKBOOTIMG_PATH"
+          else
+          echo "❌ mkbootimg not found in PATH!"
+          fi
         
-        sudo timedatectl set-timezone "${TZ}"
-        echo "status=success" >> ${GITHUB_OUTPUT}
+          sudo timedatectl set-timezone "${TZ}"
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Ensure Python build tools
         run: |
@@ -129,25 +129,25 @@ jobs:
             exit 1
           fi
 
-       - name: Load custom feeds
-         run: |
-           [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
-           chmod +x $DIY_P4_SH
-           cd openwrt
-           $GITHUB_WORKSPACE/$DIY_P4_SH
+      - name: Load custom feeds
+        run: |
+          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
+          chmod +x $DIY_P4_SH
+          cd openwrt
+          $GITHUB_WORKSPACE/$DIY_P4_SH
 
-       - name: Update & Install feeds
-         working-directory: ./openwrt
-         run: |
-           ./scripts/feeds update -a
+      - name: Update & Install feeds
+        working-directory: ./openwrt
+        run: |
+          ./scripts/feeds update -a
         
-           ./scripts/feeds install -a -f
+          ./scripts/feeds install -a -f
 
-       - name: Configuration Customization
-         run: |
+      - name: Configuration Customization
+        run: |
       
-           cp -fv "${CONFIG_FILE}" openwrt/.config
-           cd openwrt && make defconfig
+          cp -fv "${CONFIG_FILE}" openwrt/.config
+          cd openwrt && make defconfig
            
       - name: SSH 调试有效时间6h! 连接后输入q 输入exit即可退出，自动继续后续编译流程
         uses: mxschmitt/action-tmate@master
